/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Village": "村庄",
    "Village Jobs": "村庄工作",
    "Win the game!": "通关游戏！",
    "With the entirely new system colonized, your species have become interstellar. You have virtually guaranteed that the humanity will continue to exist in the future, no matter what challenges the cruel Universe and dangers lurking in its dark forest will throw at you. \n                    For the first time in the history of your village, the future seems bright and full of success.": "随着全新的系统被殖民，你们的种族已经成为星际的。你实际上已经保证了人类将在未来继续存在，无论残酷的宇宙和潜伏在黑暗森林中的危险会给你带来什么挑战。在你们村的历史上，未来第一次显得光明而成功。",
    "We can research the following technologies this turn:": "这一轮我们可以研究以下技术:",
    "When you change a law, all citizens will return to the population pool.": "当你修改一项法律时，所有的市民将回到人口池中。",
    "When you could no longer go forward in time due to the lack of resources or the attack that is going to wipe you out, your only option is to": "当你因为缺乏资源或即将消灭你的攻击而无法及时前进时，你唯一的选择就是去",
    "without resetting.": "无需重置。",
    "Workplace Shifts": "工作场所转变",
    "Total": "总计",
    "Total attacks defeated": "总计被击败次数",
    "Total Prestige resets": "总计声望重置",
    "years": "年",
    "Years passed": "度过的年份",
    "You have two options to deal with that threat. First, you can": "面对这种威胁，你有两个选择。首先，你可以",
    "The world is dark and full of dangers. Many believe that might makes right, and would not hesitate to take advantage of the weaker ones by force, or preemptively eliminate the competition.\n                                Thus, you can see a": "世界是黑暗的，充满了危险。许多人相信强权即公理，他们会毫不犹豫地用武力占弱者的便宜，或者先发制人地消灭竞争对手。\n因此，你可以看到",
    "The game is played as a sequence of turns, called": "游戏是按回合顺序进行的，叫做",
    "that you start with are perfectly capable of feeding themselves, but more advanced citizen classes will not be able to do so.\n                                You will still need to upgrade a part of your population to progress through the ages, but": "一开始，你完全有能力养活自己，但更先进的市民阶级将无法做到这一点。你仍然需要升级你的一部分人口来跨越时代，但是",
    "to match or exceed the opponent's": "赶上或超过对手",
    "Government": "政府",
    "Halfling Luck": "半身人运气",
    "Hard Reset": "硬重置",
    "Having a political capital, expressed as": "有政治资本的，表示为",
    "Help": "帮助",
    "Gain more": "获得更多",
    "Another option is to": "另一个选择是",
    "Auto-Next Year:": "自动下一年:",
    "attack": "攻击",
    "Autocracy": "独裁统治",
    "Base": "基础",
    "Convert to": "转换为",
    "Bank": "银行",
    "Current:": "当前:",
    "Economic System": "经济体系",
    "Egalitarianism ": "平等主义",
    "Export Save": "导出存档",
    "Farm": "农场",
    "Foundry": "铸造厂",
    "Free": "空闲",
    "Exile": "流放",
    "Soldier": "士兵",
    "Spend": "花费",
    "Research": "研究",
    "Replace": "替换",
    "Research is the main driver of progress, and you can perform it on the Research tab.": "研究是进展的主要驱动因素，您可以在研究选项卡上执行它。",
    "Replace one": "替换一个",
    "Regardless of the outcome of the vote, Prime Minister, as a public figure, obtains a": "无论投票结果如何，首相作为公众人物，都将获得一票",
    "Space Exploration": "太空探索",
    "Repeatable upgrades": "可重复升级",
    "Remove a citizen from the game": "从游戏中移除一个市民",
    "Raise a Child": "抚养一个孩子",
    "Prime Minister": "首相",
    "Theology": "神学",
    "Temple": "寺庙",
    "Unlock a": "解锁一个",
    "Unlock an": "解锁一个",
    "Unlock the": "解锁",
    "upkeep. Each": "维护。每一个",
    "Union Representative": "工会代表",
    "Training": "训练",
    "Totalitarianism": "极权主义",
    "To change a law, select a category first. Each category has a starting law with no effect, which you can always switch to for free, and three mutually exclusive alternatives.\n                                Selecting an alternative requires expending": "要改变一个规律，首先选择一个类别。每个类别都有一个没有效果的起始法则，你可以随时免费切换，还有三个相互排斥的选择。\n选择替代方案需要花费",
    "will happen; the strength of said attack is displayed below the meter on the left. If the attack is successful, it is game over!": "将会发生;所述攻击的强度显示在左边的仪表下方。如果攻击成功，游戏就结束了!",
    "was spent, the citizen produces": "已花费，市民生产了",
    "Send a citizen to create its copy": "派一个公民去创建它的副本",
    "Send two citizens to get another one": "派出两名市民可获得另一个",
    "The job requires a payment of": "这份工作需要支付",
    "The citizen working there must not be a": "在那里工作的公民不能是",
    "The citizen performing this job must have a": "从事这项工作的公民必须有",
    "The Final Frontier": "最后的边疆",
    "This building will do nothing if all population slots are already full.": "如果所有人口栏已满，该建筑将不做任何事情。",
    "This village job allows you to copy great minds among your population without going through genetic roulette. Unlike Raise a Child, the Clone Vats job does not combine the traits of two parents, but takes them all from a single one. However, growing a clone is costly, and requires": "这份乡村工作可以让你在不经过基因轮盘赌的情况下从你的人群中复制出伟大的思想。与“抚养孩子”不同的是，“克隆缸”的工作并没有结合两个父母的特征，而是从一个父母那里获得了所有的特征。然而，克隆是昂贵的，并且需要",
    "Will lose": "将会失败",
    "This village job is an early way of producing": "这种农村工作是一种早期的生产方式",
    "Three": "3",
    "to the current side, making it more likely to be rolled": "移到当前的一边，使它更有可能被滚动",
    "The citizens must be of the same class": "公民必须属于同一阶级",
    "technology, providing an alternate way to produce": "技术，提供了另一种生产方式",
    "technology, providing a way to produce": "技术，提供了一种生产方式",
    "them into the village building slots to produce resources.": "他们进入村庄建筑槽生产资源。",
    "This village job is a way to produce unlimited": "这种乡村工作是一种无限生产的方式",
    "Political System": "政治体系",
    "Peasant": "农民",
    "Peasants": "农民",
    "per": "每",
    "per a": "每个",
    "per attack defeated (additively).": "每次攻击失败(累加)。",
    "per die side value": "每颗骰子的价值",
    "Lumberjack": "伐木工",
    "Lose less": "损失少一些",
    "Lose all positive symbols": "失去所有正面符号",
    "Lose a": "失去一个",
    "Laborer": "劳动者",
    "Laborers": "劳动者",
    "[Space]": "[空格键]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Year ([\d\.,]+)$/, '年份 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);