/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Village": "村庄",
    "Village Jobs": "村庄工作",
    "Win the game!": "通关游戏！",
    "With the entirely new system colonized, your species have become interstellar. You have virtually guaranteed that the humanity will continue to exist in the future, no matter what challenges the cruel Universe and dangers lurking in its dark forest will throw at you. \n                    For the first time in the history of your village, the future seems bright and full of success.": "随着全新的系统被殖民，你们的种族已经成为星际的。你实际上已经保证了人类将在未来继续存在，无论残酷的宇宙和潜伏在黑暗森林中的危险会给你带来什么挑战。在你们村的历史上，未来第一次显得光明而成功。",
    "We can research the following technologies this turn:": "这一轮我们可以研究以下技术:",
    "When you change a law, all citizens will return to the population pool.": "当你修改一项法律时，所有的市民将回到人口池中。",
    "When you could no longer go forward in time due to the lack of resources or the attack that is going to wipe you out, your only option is to": "当你因为缺乏资源或即将消灭你的攻击而无法及时前进时，你唯一的选择就是去",
    "without resetting.": "无需重置。",
    "Workplace Shifts": "工作场所转变",
    "Total": "总计",
    "Total attacks defeated": "总计被击败次数",
    "Total Prestige resets": "总计声望重置",
    "years": "年",
    "Years passed": "度过的年份",
    "You have two options to deal with that threat. First, you can": "面对这种威胁，你有两个选择。首先，你可以",
    "The world is dark and full of dangers. Many believe that might makes right, and would not hesitate to take advantage of the weaker ones by force, or preemptively eliminate the competition.\n                                Thus, you can see a": "世界是黑暗的，充满了危险。许多人相信强权即公理，他们会毫不犹豫地用武力占弱者的便宜，或者先发制人地消灭竞争对手。\n因此，你可以看到",
    "The game is played as a sequence of turns, called": "游戏是按回合顺序进行的，叫做",
    "that you start with are perfectly capable of feeding themselves, but more advanced citizen classes will not be able to do so.\n                                You will still need to upgrade a part of your population to progress through the ages, but": "一开始，你完全有能力养活自己，但更先进的市民阶级将无法做到这一点。你仍然需要升级你的一部分人口来跨越时代，但是",
    "to match or exceed the opponent's": "赶上或超过对手",
    "Government": "政府",
    "Halfling Luck": "半身人运气",
    "Hard Reset": "硬重置",
    "Having a political capital, expressed as": "有政治资本的，表示为",
    "Help": "帮助",
    "Gain more": "获得更多",
    "Another option is to": "另一个选择是",
    "Auto-Next Year:": "自动下一年:",
    "attack": "攻击",
    "Autocracy": "独裁统治",
    "Base": "基础",
    "Convert to": "转换为",
    "Bank": "银行",
    "Current:": "当前:",
    "Economic System": "经济体系",
    "Egalitarianism": "平等主义",
    "Export Save": "导出存档",
    "Farm": "农场",
    "Foundry": "铸造厂",
    "Free": "空闲",
    "Exile": "流放",
    "Soldier": "士兵",
    "Spend": "花费",
    "Research": "研究",
    "Replace": "替换",
    "Research is the main driver of progress, and you can perform it on the Research tab.": "研究是进展的主要驱动因素，您可以在研究选项卡上执行它。",
    "Replace one": "替换一个",
    "Regardless of the outcome of the vote, Prime Minister, as a public figure, obtains a": "无论投票结果如何，首相作为公众人物，都将获得一票",
    "Space Exploration": "太空探索",
    "Repeatable upgrades": "可重复升级",
    "Remove a citizen from the game": "从游戏中移除一个市民",
    "Raise a Child": "抚养一个孩子",
    "Prime Minister": "首相",
    "Theology": "神学",
    "Temple": "寺庙",
    "Unlock a": "解锁一个",
    "Unlock an": "解锁一个",
    "Unlock the": "解锁",
    "upkeep. Each": "维护。每一个",
    "Union Representative": "工会代表",
    "Training": "训练",
    "Totalitarianism": "极权主义",
    "To change a law, select a category first. Each category has a starting law with no effect, which you can always switch to for free, and three mutually exclusive alternatives.\n                                Selecting an alternative requires expending": "要改变一个规律，首先选择一个类别。每个类别都有一个没有效果的起始法则，你可以随时免费切换，还有三个相互排斥的选择。\n选择替代方案需要花费",
    "will happen; the strength of said attack is displayed below the meter on the left. If the attack is successful, it is game over!": "将会发生;所述攻击的强度显示在左边的仪表下方。如果攻击成功，游戏就结束了!",
    "was spent, the citizen produces": "已花费，市民生产了",
    "Send a citizen to create its copy": "派一个公民去创建它的副本",
    "Send two citizens to get another one": "派出两名市民可获得另一个",
    "The job requires a payment of": "这份工作需要支付",
    "The citizen working there must not be a": "在那里工作的公民不能是",
    "The citizen performing this job must have a": "从事这项工作的公民必须有",
    "The Final Frontier": "最后的边疆",
    "This building will do nothing if all population slots are already full.": "如果所有人口栏已满，该建筑将不做任何事情。",
    "This village job allows you to copy great minds among your population without going through genetic roulette. Unlike Raise a Child, the Clone Vats job does not combine the traits of two parents, but takes them all from a single one. However, growing a clone is costly, and requires": "这份乡村工作可以让你在不经过基因轮盘赌的情况下从你的人群中复制出伟大的思想。与“抚养孩子”不同的是，“克隆缸”的工作并没有结合两个父母的特征，而是从一个父母那里获得了所有的特征。然而，克隆是昂贵的，并且需要",
    "Will lose": "即将失败",
    "This village job is an early way of producing": "这种农村工作是一种早期的生产方式",
    "Three": "3",
    "to the current side, making it more likely to be rolled": "移到当前的一边，使它更有可能被滚动",
    "The citizens must be of the same class": "公民必须属于同一阶级",
    "technology, providing an alternate way to produce": "技术，提供了另一种生产方式",
    "technology, providing a way to produce": "技术，提供了一种生产方式",
    "them into the village building slots to produce resources.": "他们进入村庄建筑槽生产资源。",
    "This village job is a way to produce unlimited": "这种乡村工作是一种无限生产的方式",
    "Political System": "政治体系",
    "Peasant": "农民",
    "Peasants": "农民",
    "per": "每",
    "per a": "每个",
    "per attack defeated (additively).": "每次攻击失败(累加)。",
    "per die side value": "每颗骰子的价值",
    "Lumberjack": "伐木工",
    "Lose less": "损失少一些",
    "Lose all positive symbols": "失去所有正面符号",
    "Lose a": "失去一个",
    "Laborer": "劳动者",
    "Laborers": "劳动者",
    "[Space]": "[空格键]",
    "Random": "随机",
    "Religion": "宗教",
    "resources": "资源",
    "Retraining": "再训练",
    "Reload Start of Year": "重新加载开始年份",
    "represent the total amount of work done installing and connecting the solar panels; for each": "表示安装和连接太阳能电池板的总工作量;为每一个",
    "represent the total amout of work done constructing and launching additional space probes; for each": "表示建造和发射额外空间探测器的总工作量;为每一个",
    "Remove all": "全部移除",
    "removes all": "全部移除",
    "Reset now to gain": "现在重置获得",
    "Scientists": "科学家",
    "Scientist": "科学家",
    "Self-Sufficiency": "自给自足",
    "Serfdom": "农奴制",
    "Social System": "社会制度",
    "Solar Panels": "阳能电池板",
    "Specialists": "专家",
    "Specialist Training": "专家培训",
    "symbol gets a job in the village itself; then, they cannot travel to other places and tell them of your riches, so no Notice will actually be produced.\n                                However, no other resources this citizen rolled will be produced either.": "象征在村子里找到了工作;然后，他们就不能去其他地方告诉他们你的财富，所以实际上不会产生通知。然而，这个公民掷出的其他资源也不会产生。",
    "Only": "只有",
    "only": "只有",
    "Notice meter": "通知计",
    "No effect.": "没有效果。",
    "No effect": "没有效果",
    "Notice and Attacks": "通知与攻击",
    "Next when you successfully defend against the next attack": "接下来，当你成功抵御下一次攻击时",
    "Military Training": "军事训练",
    "Off": "关闭",
    "Oil Derrick": "石油井架",
    "Oil Powerplant": "石油动力装置",
    "Oil Refinery": "炼油厂",
    "On": "打开",
    "Overview and Basics": "概述和基础知识",
    "prestige": "声望",
    "Prestige": "声望",
    "Prestige resets you back at the start of year 1, but you get a new currency,": "声望会让你回到第一年的起点，但你会得到一种新的货币，",
    "Priest": "牧师",
    "Priests": "牧师",
    "production": "生产",
    "produces": "生产",
    "Produce": "生产",
    "produce progress": "生产进度",
    "Produce resources other than": "生产以外的资源",
    "production. The citizen employed there has a 10% chance, multiplied by the number on the rolled die side (from 10% to 60%), to gain a": "生产。在那里工作的公民有10%的机会，乘以掷出的骰子的数量(从10%到60%)，获得一个",
    "Needs": "需要",
    "Needs to have oil": "需要石油",
    "Next Year": "下一年",
    "Next:": "下一个:",
    "On fill become": "填满成为",
    "on various upgrades.": "在各种升级上。",
    "Market Caravan": "市场商队",
    "Monochrome": "黑白",
    "Laws": "法律",
    "Mayor": "市长",
    "Mint": "铸币厂",
    "If the vote is above 50%, Prime Minisher has a chance to learn a thing or two about governance: there is a chance equal to support level minus 50% that one of the": "如果投票超过50%，首相有机会学习一些关于治理的东西:有机会等于支持等级减去50%",
    "Democracy": "民主",
    "Events no longer happen at the cost of": "事件的发生不再需要花费",
    "Every citizen requires an upkeep of": "每个公民都需要保养",
    "Every year, your researches come mp with a selection of three technologies that you can possibly research. This selection is random and changs every year.\n                                To research a technology, you need enough": "每年，你的研究报告都会附带三种你可能研究的技术。这个选择是随机的，每年都在变化。要研究一项技术，你需要足够的东西",
    "Feudalism": "封建主义",
    "First Strike": "先发制人",
    "Governance": "统治方式",
    "gain is equal to square the number of attacks you successfully defeated plus the progress towards defeating the next attack; this gain and many other aspects of your settlement can be improved by spending": "收益等于你成功击败的攻击次数的平方加上战胜下一次攻击的进度;这种收益和你定居的许多其他方面都可以通过消费来改善",
    "Copy your save from the textbox below:": "从下面的文本框复制你的存档:",
    "Decrease chance of negative events based on unspent": "基于未花费减少负面事件的机会",
    "Copy random symbol onto a free citizen": "将随机符号复制到一个自由公民身上",
    "Continue playing": "继续游戏",
    "Check more games from me on": "查看我的更多游戏在",
    "Citizen Classes": "公民阶层",
    "Color theme:": "颜色主题：",
    "Clone Vats": "克隆桶",
    "Construct Generational Ship": "构建代际关系",
    "Congratulations!": "恭喜！",
    "Caste System": "种姓制度",
    "Each technology researched reduces": "研究的每一项技术都减少了",
    "from that side are distributed among the unemployed population at random, making sure they can be used again in the resource-producing buildings. The side of the worker that actually took the Union Representative job is left devoid of": "从那边随机分配给失业人口，确保它们可以再次用于生产资源的建筑。真正接受了工会代表工作的那一方工人没有",
    "Each technology researched has a chance to increase": "每一项被研究的技术都有增加的机会",
    "Import Save": "导入存档",
    "Dark": "深色",
    "Paste your save into the textbox below and click \"Import\":": "将你的存档粘贴到下面的文本框中，然后点击“导入”:",
    "A citizen who is employed there produces": "在那里工作的公民生产",
    "and can be specialized into the production of a resource by working in resource-producing jobs.\n                                They start with a": "并且可以通过从事生产资源的工作而专门从事生产资源的工作。\ n                                 他们开始用",
    "and advancing your progress.\n                                It is usually a good idea to make Scientists out of fresh Laborers to maximize": "并促进你的进步。把新鲜的劳动者培养成科学家通常是个好主意",
    "and consumes": "和消耗",
    "and get resources": "并获得资源",
    "All jobs get a second slot.": "所有工作得到第二个槽。",
    "Aggressive Isolationism": "激进孤立主义",
    "A Jealous Nearby Tribe": "附近一个嫉妒的部落",
    "Academia": "学术领域",
    "Add": "添加",
    "Advisor": "顾问",
    "to the 6 side": "到 6 边",
    "Barter": "易货交易",
    "Build a Wall": "建造一堵墙",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "limit by ": "限制为 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Year ([\d\.,]+)$/, '年份 $1'],
    [/^Resets on Year ([\d\.,]+)$/, '重置到年份 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Needs to roll a ([\d\.,]+)$/, '需要掷出 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);